### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by gitusqq** [Keelhauled/KeelPlugins#13]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
KeelPlugins.TitleShortcutsCore.get_StartupArgument () (at <d6058acdfde047ff93ec55d452d3a690>:0)
KeelPlugins.TitleShortcuts+<InputCheck>d__28.MoveNext () (at <d6058acdfde047ff93ec55d452d3a690>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <0a7d89e4511e4bdeb215f76ca00fd04e>:0)

**Comment by Keelhauled** [comment]
This is apparently an issue in the steam version, I won't be able to debug this.

**Comment by Keelhauled** [comment]
@Mantas-2155X You made this right :)

**Comment by Mantas-2155X** [comment]
This can't be an issue in the Steam version because the process filter is "AI-Syoujyo" (JP Version) so it wouldn't even attempt to start in the Steam game unless the filter was taken out manually.

Please provide steps to reproduce the issue, just the error doesn't tell me much.

**Comment by Mantas-2155X** [comment]
@Keelhauled :)
