### ISSUE TITLE
TitleShortcuts - Disable the "fast startup"

### ISSUE THREAD

**Issue by Matihood1** [Keelhauled/KeelPlugins#17]
So in addition to its described features, the TitleShortcuts plugin also has this whole "fast startup" where it skips the "Illusion" voice line at the game startup and makes the game launch slightly faster because of that. However, I'm not a big fan of that and I'd like to have an option for it to be disabled (from what I've seen, there's no such setting).

**Comment by Keelhauled** [comment]
Marco has made a new repo to contain fast start code and all that code will be removed from TitleShortcuts. https://github.com/IllusionMods/IntroBegone
