### ISSUE TITLE
HS2_ Lockon Plugin for Honey Select 2

### ISSUE THREAD

**Issue by ashealba** [Keelhauled/KeelPlugins#18]
I have no idea how this gitbhub place works. But I did wanna leave a message/request for the mod dev. Honey Select 2 VERY MUCH needs a way to configure a series of preset camera angles during scenes. The user can align their camera, freeze that viewpoint as a camera preset, define a hotkey for it (or just cycle through a list of camera presets already saved), then watch a scene from varying camera viewpoints.

Can this be done?

Also, could use a third-person mode (showing the male character) standing there during dialogues. Just FYI! :)

**Comment by Keelhauled** [comment]
Not interested in making HS2 mods sorry
